import { IoIosArrowBack } from "react-icons/io";
import { Link } from "react-router-dom";


const EarthDescription = () => {
    return (
        <div className="bg-black text-white">
            <div className="h-screen" style={{ backgroundImage: `url('../../public/earth.png')`, backgroundSize: "cover", backgroundPosition: "center", backgroundRepeat: "no-repeat" }}>
            </div>

            

            <h1 className="text-4xl font-bold my-8 text-center font-blackOp">Description</h1>

            <div className="p-8 w-10/12 mx-auto font-kurale">

                <div className="space-y-6">
                    {/* 1. Gravity */}
                    <section>
                        <h2 className="text-2xl font-semibold text-yellow-400">1. Gravity</h2>
                        <p>Surface gravity on Earth: 9.8 m/s²</p>
                    </section>

                    {/* 2. Ratio of Water and Land */}
                    <section>
                        <h2 className="text-2xl font-semibold text-yellow-400">2. Ratio of Water and Land</h2>
                        <p>Earth's surface is about 71% water and 29% land.</p>
                    </section>

                    {/* 3. Weight (Mass) of Earth */}
                    <section>
                        <h2 className="text-2xl font-semibold text-yellow-400">3. Weight (Mass) of Earth</h2>
                        <p>Earth's mass: Approximately 5.97 × 10²⁴ kg</p>
                    </section>

                    {/* 4. Radius of Earth */}
                    <section>
                        <h2 className="text-2xl font-semibold text-yellow-400">4. Radius of Earth</h2>
                        <p>Equatorial radius: 6,378.1 km</p>
                        <p>Polar radius: 6,356.8 km</p>
                    </section>

                    {/* 5. Gases in the Atmosphere */}
                    <section>
                        <h2 className="text-2xl font-semibold text-yellow-400">5. Gases in the Atmosphere</h2>
                        <ul className="list-disc list-inside">
                            <li>Nitrogen (N₂): ~78%</li>
                            <li>Oxygen (O₂): ~21%</li>
                            <li>Argon (Ar): ~0.93%</li>
                            <li>Carbon Dioxide (CO₂): ~0.04%</li>
                            <li>Trace amounts of neon, helium, methane, krypton, and hydrogen</li>
                        </ul>
                    </section>

                    {/* 6. Atmospheric Layers */}
                    <section>
                        <h2 className="text-2xl font-semibold text-yellow-400">6. Atmospheric Layers</h2>
                        <ul className="list-disc list-inside">
                            <li>Troposphere: 0-12 km (where weather occurs)</li>
                            <li>Stratosphere: 12-50 km (contains the ozone layer)</li>
                            <li>Mesosphere: 50-85 km</li>
                            <li>Thermosphere: 85-600 km</li>
                            <li>Exosphere: 600 km and above (merges into space)</li>
                        </ul>
                    </section>

                    {/* 7. Magnetic Field */}
                    <section>
                        <h2 className="text-2xl font-semibold text-yellow-400">7. Magnetic Field</h2>
                        <p>
                            Earth has a strong magnetic field generated by its molten iron core, which protects the planet from solar wind and cosmic radiation.
                        </p>
                    </section>

                    {/* 8. Temperature */}
                    <section>
                        <h2 className="text-2xl font-semibold text-yellow-400">8. Temperature</h2>
                        <p>Average surface temperature: ~15°C (59°F)</p>
                        <p>Temperature varies widely depending on location and time of year.</p>
                    </section>

                    {/* 9. Tilt and Rotation */}
                    <section>
                        <h2 className="text-2xl font-semibold text-yellow-400">9. Tilt and Rotation</h2>
                        <p>Axial tilt: 23.5° (responsible for the seasons)</p>
                        <p>Rotation period (length of a day): 24 hours</p>
                    </section>

                    {/* 10. Orbital Characteristics */}
                    <section>
                        <h2 className="text-2xl font-semibold text-yellow-400">10. Orbital Characteristics</h2>
                        <p>Orbital Period (Year Length): 365.25 days (1 year)</p>
                        <p>Orbital Speed: Approximately 29.78 km/s</p>
                        <p>Distance from the Sun: Average of 149.6 million km (1 Astronomical Unit)</p>
                    </section>

                    {/* 11. Atmospheric Pressure */}
                    <section>
                        <h2 className="text-2xl font-semibold text-yellow-400">11. Atmospheric Pressure</h2>
                        <p>Average sea-level atmospheric pressure: 101.3 kPa (kilopascals) or 1 atmosphere (atm)</p>
                    </section>
                </div>
            </div>

            <div className="w-11/12 mx-auto py-5">
                <Link to='/earth'><IoIosArrowBack className="text-6xl" /></Link>
            </div>
        </div>
    );
};

export default EarthDescription;